[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
session_state = "FJwbNTbGHSpq4a72ro1aza53kvs7YMNT7J5U34kaosFj"
hidden_state = "Ea3VKF8CW3svQwiT8pn13JVdbVhLHSBURtNuanagc4hs"
input_buffer = "3R2RbzwP54qdyXcyiwHW2Sj6uVwf4Dhy7Zy8RcSVHFpq"
frame_log = "3mWTNv5jhzLnpG4Xt9XqM1b2nbNpizoGEJxepUhhoaNK"
model_manifest = "AucQsnqWYXeVcig4puWFjnd8NXruCtjS8EVgA2B5KxUk"
weight_shard = "A56nQANMn1ThuqZLZkAVooDmUMrSoEddyNHF41WbqvXE"
session_lifecycle = "4ozheJvvMhG7yMrp1UR2kq1fhRvjXoY5Pn3NJ4nvAcyE"
submit_input = "F9ZqWHVDtsXZdHLU8MXfybsS1W3TTGv4NegcJZK9LnWx"
run_inference = "3tHPJJSNhKwbp7K5vSYCUdYVX9bGxRCmpddwaJWRKPyb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs-ecs/components/*", "programs-ecs/systems/*"]

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

# BOLT World program â€” required for all ECS operations
[[test.genesis]]
address = "WorLD15A7CrDwLcLy4fRqtaTb9fbd8o8iqiEMUDse2n"
program = "tests/fixtures/world.so"
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://rpc.magicblock.app/devnet/"
ledger = ".bolt/test-ledger"
rpc_port = 8899

# BOLT registry account
[[test.validator.account]]
address = "EHLkWwAT9oebVv9ht3mtqrvHhRVMKrt54tF3MfHTey2K"
filename = "tests/fixtures/registry.json"
